image: ubuntu:16.04

stages:
  - build
  - tests
# - api-tests
# - ui-tests
# - artifacts

default:
  before_script:
    - apt-get update -y
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk version
    - sdk ls java
    - sdk install java 11.0.7-open


build:
  stage: build
  script:
    - ./gradlew assemble

ui-tests:
  stage: tests
  script:
    - ./gradlew test allureReport